const Data = [
  {
    id: 1,
    image: require("./imgs/shops-1.png"),
    name: "Mapple Earphones",
    price: "180",
    discount: "25",
    category: "airpods",
  },
  {
    id: 2,
    image: require("./imgs/shops-2.png"),
    name: "Vivo android one",
    price: "120",
    discount: "10",
    category: "oppo",
  },
  {
    id: 3,
    image: require("./imgs/shops-3.png"),
    name: "Sony Light",
    price: "20",
    discount: "50",
    category: "cap",
  },
  {
    id: 4,
    image: require("./imgs/shops-4.png"),
    name: "Iphone",
    price: "999",
    discount: "10 ",
    category: "iphone",
  },
  {
    id: 5,
    image: require("./imgs/shops-5.png"),
    name: "Ceats wireless earphone",
    price: "80",
    discount: "20",
    category: "airpods",
  },
  {
    id: 6,
    image: require("./imgs/shops-7.png"),
    name: "Redimi Phone",
    price: "400",
    discount: "20 ",
    category: "redimi",
  },
  {
    id: 7,
    image: require("./imgs/shops-8.png"),
    name: "Xeats Bluetooth earphones",
    price: "60",
    discount: "5",
    category: "airpods",
  },
  {
    id: 8,
    image: require("./imgs/shops-9.png"),
    name: "Airpod",
    price: "120",
    discount: "10",
    category: "airpods",
  },
  {
    id: 9,
    image: require("./imgs/shops-10.png"),
    name: "Silver Cap",
    price: "5",
    discount: "2",
    category: "cap",
  },
];
export default Data;
